-- MySQL Script generated by MySQL Workbench
-- Mon Dec 22 22:30:18 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ps_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ps_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ps_schema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ps_schema` ;

-- -----------------------------------------------------
-- Table `ps_schema`.`ps_searches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ps_schema`.`ps_searches` ;

CREATE TABLE IF NOT EXISTS `ps_schema`.`ps_searches` (
  `ps_search_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `ps_search_query` VARCHAR(255) NULL,
  `kaymu_search` TINYINT(1) NULL,
  `tonaton_search` TINYINT(1) NULL,
  `olx_search` TINYINT(1) NULL,
  `search_timestamp` TIMESTAMP(45) NULL,
  PRIMARY KEY (`ps_search_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ps_schema`.`tonaton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ps_schema`.`tonaton` ;

CREATE TABLE IF NOT EXISTS `ps_schema`.`tonaton` (
  `ps_tonaton_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `tn_item_name` VARCHAR(255) NULL,
  `tn_price` VARCHAR(45) NULL,
  `tn_location` VARCHAR(45) NULL,
  `tn_item_link` VARCHAR(255) NULL,
  `tn_date_created` TIMESTAMP(45) NULL,
  PRIMARY KEY (`ps_tonaton_id`),
  UNIQUE INDEX `ps_tonaton_UNIQUE` (`ps_tonaton_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ps_schema`.`olx`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ps_schema`.`olx` ;

CREATE TABLE IF NOT EXISTS `ps_schema`.`olx` (
  `ps_olx_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `ol_item_name` VARCHAR(45) NULL,
  `ol_price` VARCHAR(45) NULL,
  `ol_location` VARCHAR(45) NULL,
  `ol_item_link` VARCHAR(255) NULL,
  `ol_date_created` TIMESTAMP(45) NULL,
  PRIMARY KEY (`ps_olx_id`),
  UNIQUE INDEX `ps_olx_id_UNIQUE` (`ps_olx_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ps_schema`.`kaymu_ghana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ps_schema`.`kaymu_ghana` ;

CREATE TABLE IF NOT EXISTS `ps_schema`.`kaymu_ghana` (
  `ps_km_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `km_item_name` VARCHAR(255) NULL,
  `km_price` VARCHAR(45) NULL,
  `km_location` VARCHAR(45) NULL,
  `km_item_link` VARCHAR(255) NULL,
  `km_date_created` TIMESTAMP(45) NULL,
  PRIMARY KEY (`ps_km_id`),
  UNIQUE INDEX `ps_km_id_UNIQUE` (`ps_km_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
